set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g status-interval 5
setw -g mode-keys vi
bind r source-file ~/.tmux.conf \; display-message "tmux config recargada"
bind | split-window -h
bind - split-window -v
